name: Build container image and push to Dockerhub

on:
  push:
    tags: [ 'v*' ]
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Write the computed version (from the tag plus any newer commits) to it gets embedded into the binary
        run: ./misc/version_from_git_tags.bash > version

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ github.event_name != 'pull_request'
              && format('{0}/{1}:latest,{0}/{1}:{2}',
                  vars.DOCKERHUB_USERNAME,
                  vars.DOCKERHUB_IMAGE_NAME,
                  github.ref_name)
              || ''
            }}

      - name: Save the tag that was just pushed to Dockerhub
        run: echo "${{ github.event_name != 'pull_request' && github.ref_name || '' }}" > dockerhub_image_latest_tag

      - name: Upload dockerhub_image_latest_tag
        uses: actions/upload-artifact@v4
        with:
          name: dockerhub_image_latest_tag
          path: dockerhub_image_latest_tag
          overwrite: true
          retention-days: 1
